name: MasterCI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          npm i
          npm run setup

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          node-version: '10.x'
      - run: |
          npm i
          npm run setup
          npm run test

  publish_api:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          ls -lha
          cd ./api
          ls -lha
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.EMAIL}}

  publish_client:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          ls -lha
          cd ./client
          ls -lha
          npm i
          npm run build
          npm install -g surge
          surge ./build/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
