name: MasterCI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          npm i
          npm run setup

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          node-version: '12.x'
      - run: |
          npm i
          npm run setup
          npm run test

  publish_api:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: akhileshns/heroku-deploy@v3.3.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "api"

  publish_client:
    needs: [test, publish_api]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        env:
          REACT_APP_API_ENDPOINT: ${{ secrets.REACT_APP_API_ENDPOINT }}
          REACT_APP_NAME: ${{ secrets.REACT_APP_NAME }}
          REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}
      - run: |
          cd ./client
          echo ${{ secrets.REACT_APP_ENV }} > .env
          export REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_ENDPOINT }}
          export REACT_APP_NAME=${{ secrets.REACT_APP_NAME }}
          export REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}
          npm i
          npm run build
          npm install -g surge
          surge ./build/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
